name: TechZone CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Build Solution
      run: dotnet build --configuration Release

    - name: Containerize Application
      run: docker build -t techzone-app:latest .